name: Build

on:
  - push
  - pull_request

jobs:
  unit:
    strategy:
      matrix:
        ruby_version:
          - '3.1'
          - '3.0'
          - '2.7'
          - 'jruby-9.3.3.0'
        gemfile:
          - gemfiles/rails_70.gemfile
          - gemfiles/rails_61.gemfile
          - gemfiles/rails_60.gemfile
    runs-on: ubuntu-18.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake test

  system:
    needs: unit
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Install dependencies
        run: |
          rm -rf node_modules &&
          yarn install &&
          yarn add tslib &&
          bundle
      - name: Run the system test in the dummy app
        run: rake test:system

  rails_edge:
    needs: system
    runs-on: ubuntu-18.04
    env:
      BUNDLE_GEMFILE: gemfiles/rails_edge.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - run: bundle exec rake test || echo "Rails edge test is done."

  ruby_edge:
    needs: system
    strategy:
      matrix:
        gemfile:
          - gemfiles/rails_edge.gemfile
          - gemfiles/rails_70.gemfile
    runs-on: ubuntu-18.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'ruby-head'
          bundler-cache: true
      - run: bundle exec rake || echo "Ruby edge test is done."

#  browser_tests:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.1.0
#          bundler-cache: true
#      - name: Install dependencies
#        run: |
#          rm -rf node_modules &&
#          yarn install &&
#          yarn add tslib &&
#          bundle
#      - name: 'BrowserStack Env Setup'
#        uses: 'browserstack/github-actions/setup-env@master'
#        with:
#          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
#          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
#      - name: 'Start BrowserStackLocal Tunnel'
#        uses: 'browserstack/github-actions/setup-local@master'
#        with:
#          local-testing: 'start'
#          local-logging-level: 'all-logs'
#          local-identifier: 'random'
#      - name: Run the system test in the dummy app
#        run: rake test:system
#        env:
#          BROWSERSTACK_URL:  ${{ secrets.BROWSERSTACK_URL }}
#      - name: 'Stop BrowserStackLocal'
#        uses: 'browserstack/github-actions/setup-local@master'
#        with:
#          local-testing: 'stop'
